### ISSUE TITLE
What is the recommended way to add AugmentKit to another project?

### ISSUE THREAD

**Issue by KTRosenberg** [JamieScanlon/AugmentKit#10]
I’m looking forward to trying this project within another existing Xcode project I have set-up. There are several project and workspace files here. What is the simplest/most straightforward way to add and use AugmentKit in an Xcode project? Thank you for your time.

**Comment by JamieScanlon** [comment]
Sure. I'll get the process easer eventually. For now
- Create a new project in your Workspace called AugmentKit. Set it up as a Framework
- Copy over all of the files in the AugmentKit directory of your GitHub project clone
- In the build settings for your AugmentKit framework target add the following to the `Import Paths` 
  - $(SRCROOT)/AugmentKit/Renderer
- In your main project ad your AugmentKit.framework as an embedded library

Refer to the AugmentKit2 project in your GitHub clone if you get stuck
